### ISSUE TITLE
Link in README.md is broken ("Required node_exporter Configuration")

### ISSUE THREAD

**Issue by bluepuma77** [galexrt/container-node_exporter-textfiles#14]
Link in README.md is broken
```
Required node_exporter Configuration

See [node_exporter Configuration Prerequisites](https://github.com/galexrt/container-node_exporter-textfiles/blob/main/node_exporter.md).
```

I am new to node-exporter-textfiles and looking into retrieving smartmon data. Wondering why the textfile is passed through node-exporter instead of just running a slim web-server providing the file contents. Running several prometheus containers (node-exporter, cadvisor) in Docker Swarm anyway, prometheus could just automatically scape it directly.

**Comment by galexrt** [comment]
Thanks for bringing the broken link to my attention, it has been fixed now!

> Wondering why the textfile is passed through node-exporter instead of just running a slim web-server providing the file contents.

It is simply one (common) way to get these textfile metrics into Prometheus without having to run an additional service/component, such as a (slim) webserver.
If I personally don't have to run an "additional" webserver on a server and can utilize an already existing/running component (node_exporter), I would just use that instead of having to maintain an additional component (webserver) to get the job done.
